"""Build the fit-comparison table for the full-posterior fit diagnostics.

The report has always described an in-sample plug-in fit score but never tabulated it,
and it listed a predictive comparison as future work.  The forward-filtered scores in
``production/main_scripts/predictive_comparison.py`` still use parameters drawn from the full-sample
posterior, so none is a genuine prequential or out-of-sample score.  WAIC and PSIS-LOO
are additionally nonstandard because the inputs are conditional filtering densities,
not the pointwise likelihood used to fit the posterior.

Reads results/evidence/tables/predictive_comparison.csv (written by
production/main_scripts/predictive_comparison.py) and writes the LaTeX fragment the report inputs.

    python production/main_scripts/predictive_comparison.py      # first
    python production/main_scripts/make_fit_comparison_table.py  # then
"""
from __future__ import annotations

from pathlib import Path

import pandas as pd

import _bootstrap  # noqa: F401
from _bootstrap import RESULTS_DIR, ROOT
from nkpc_hsa.inference.wrappers import ESTIMATION_REVISION

SRC = RESULTS_DIR / "evidence" / "tables" / "predictive_comparison.csv"
OUT = RESULTS_DIR / "tables" / "annual_q4"
LABELS = {"ces": "CES", "hsa_steady": "HSA steady", "hsa_dynamic": "HSA dynamic",
          "hsa_full": "HSA full"}
ORDER = ["ces", "hsa_steady", "hsa_dynamic", "hsa_full"]
PRICES = ["Core CPI", "Headline CPI", "PPI"]


def main() -> None:
    if not SRC.exists():
        raise SystemExit(f"missing {SRC}; run production/main_scripts/predictive_comparison.py first")
    table = pd.read_csv(SRC)
    if "estimation_revision" not in table or set(table["estimation_revision"].dropna()) != {ESTIMATION_REVISION}:
        raise SystemExit(
            f"{SRC} is stale or has no estimation revision; rerun production/main_scripts/predictive_comparison.py"
        )
    main_design = table[table["design"] == "annual_q4"]
    if main_design.empty:
        raise SystemExit("predictive_comparison.csv has no annual_q4 rows")

    lines = [
        r"\begin{table}[H]", r"\centering",
        (r"\caption{Fit comparison for the negative unemployment gap, mixed-frequency "
         r"design. All four columns are log scores, so higher is better, and all are "
         r"differences against nothing---only comparisons within a price index are "
         r"meaningful. \emph{Plug-in} is the in-sample score of the text: the inflation "
         r"equation evaluated at posterior-mean parameters and states, scored by a "
         r"Gaussian log-likelihood at the posterior-mean shock variance. "
         r"\emph{FF-LPD} is a one-step forward-filtered conditional log density, "
         r"integrated over full-sample posterior draws; it is not prequential because "
         r"those parameter draws have seen all observations. Heuristic WAIC and "
         r"PSIS-LOO apply their usual transforms to these filtering densities and are "
         r"not standard WAIC or LOO. "
         r"$\hat k$ is the maximum Pareto shape for the LOO importance weights; "
         r"$\hat k>0.7$ marks a cell where LOO is unreliable.}"),
        r"\label{tab:fit-comparison}", r"\small",
        r"\begin{tabular}{llccccc}", r"\toprule",
        (r"Price & Model & Plug-in & FF-LPD & hWAIC & hPSIS-LOO & $\hat k$ \\"),
        r"\midrule",
    ]
    for price in PRICES:
        sub = main_design[main_design["price"] == price].set_index("model")
        for i, model in enumerate(ORDER):
            if model not in sub.index:
                continue
            r = sub.loc[model]
            flag = r"\textsuperscript{$\ast$}" if float(r["max_pareto_k"]) > 0.7 else ""
            cells = [
                price if i == 0 else "",
                LABELS[model],
                f"{r['plugin_score']:.2f}",
                f"{r['LPD_1step']:.2f}",
                f"{r['WAIC']:.2f}",
                f"{r['LOO']:.2f}" + flag,
                f"{r['max_pareto_k']:.2f}",
            ]
            if model == "hsa_steady":
                cells = [r"\textbf{" + c + "}" if c else c for c in cells]
            lines.append(" & ".join(cells) + r" \\")
        lines.append(r"\midrule")
    lines[-1] = r"\bottomrule"
    lines += [r"\end{tabular}", r"\end{table}", ""]

    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "fit_comparison.tex").write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {(OUT / 'fit_comparison.tex').relative_to(ROOT)}")

    # The numbers the report quotes in prose. They are emitted as macros for the
    # same reason as everything else in the body text: a re-run must move the
    # sentences, not just the table. See the macro note in nkpc_hsa_report.tex.
    keys = {"Core CPI": "Core", "Headline CPI": "Headline", "PPI": "PPI"}
    scores = {"plugin_score": "Plugin", "LPD_1step": "Lpd", "WAIC": "Waic", "LOO": "Loo"}
    macros = ["% Generated by production/main_scripts/make_fit_comparison_table.py; do not edit by hand."]
    ratios = []
    for price in PRICES:
        sub = main_design[main_design["price"] == price].set_index("model")
        if "ces" not in sub.index or "hsa_steady" not in sub.index:
            continue
        c, h = sub.loc["ces"], sub.loc["hsa_steady"]
        for column, name in scores.items():
            diff = float(h[column]) - float(c[column])
            macros.append(rf"\providecommand{{\Fit{keys[price]}{name}Diff}}{{{diff:+.2f}}}")
        plugin = float(h["plugin_score"]) - float(c["plugin_score"])
        lpd = float(h["LPD_1step"]) - float(c["LPD_1step"])
        if abs(lpd) > 1e-9 and price != "PPI":
            ratios.append(plugin / lpd)
        print(f"  {price:13s} HSA steady - CES:  plug-in {plugin:+6.2f}"
              f"   LPD1 {lpd:+6.2f}"
              f"   WAIC {float(h['WAIC'])-float(c['WAIC']):+6.2f}"
              f"   LOO {float(h['LOO'])-float(c['LOO']):+6.2f}")
    # How unreliable the LOO column is: cells whose Pareto k exceeds the 0.7 rule.
    flagged = main_design[main_design["max_pareto_k"] > 0.7]
    macros.append(rf"\providecommand{{\FitLooCellCount}}{{{len(main_design)}}}")
    macros.append(rf"\providecommand{{\FitLooFlaggedCount}}{{{len(flagged)}}}")
    if ratios:
        macros.append(rf"\providecommand{{\FitPluginOverstateMin}}{{{min(ratios):.1f}}}")
        macros.append(rf"\providecommand{{\FitPluginOverstateMax}}{{{max(ratios):.1f}}}")
    macro_path = RESULTS_DIR / "tables" / "shared" / "fit_comparison_macros.tex"
    macro_path.parent.mkdir(parents=True, exist_ok=True)
    macro_path.write_text("\n".join(macros) + "\n", encoding="utf-8")
    print(f"wrote {macro_path.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
