"""Turn the conditional-marginal-likelihood run into the report's table and macros.

Reads results/evidence/tables/conditional_ml.csv (written by
scripts/chib_marginal_likelihood.py) and writes the LaTeX fragment the report
inputs plus the macros the prose quotes.

The table reports the components, not only the Bayes factor. log m(N) and log m(x)
are Occam factors for data the comparison conditions on: they are charged in the
joint term and refunded in the conditional one, and showing them is what makes
visible that both models are debited the identical m(x).

    python scripts/chib_marginal_likelihood.py --all-cells   # first
    python scripts/make_conditional_ml_table.py              # then
"""
from __future__ import annotations

import numpy as np
import pandas as pd

import _bootstrap  # noqa: F401
from _bootstrap import ROOT

SRC = ROOT / "results" / "evidence" / "tables" / "conditional_ml.csv"
OUT = ROOT / "results" / "tables" / "annual_q4"
MACROS = ROOT / "results" / "tables" / "shared" / "conditional_ml_macros.tex"

PRICES = ["Headline CPI", "Core CPI", "PPI"]
ACTIVITIES = ["Unemployment gap", "HP output gap", "BN output gap"]
MAIN = ("Core CPI", "Unemployment gap")


def main() -> None:
    if not SRC.exists():
        raise SystemExit(
            f"missing {SRC}; run scripts/chib_marginal_likelihood.py --all-cells first"
        )
    table = pd.read_csv(SRC)
    ok = table[table["error"].isna()] if "error" in table else table
    if ok.empty:
        raise SystemExit(f"{SRC} has no identified cells")

    lines = [
        r"\begin{table}[H]", r"\centering",
        (r"\caption{Conditional marginal likelihood, CES versus HSA steady, "
         r"mixed-frequency design, baseline priors. Each row is "
         r"$\log p(\pi\mid x, N^{\mathrm{obs}}, M)$ for the two models and their "
         r"difference. The two subtracted columns are Occam factors for data the "
         r"comparison conditions on: $\log m(N^{\mathrm{obs}})$ for the firm-count "
         r"block, which CES does not have, and $\log m(x)$ for the activity "
         r"equation, which is identical for the two models and is computed once per "
         r"cell rather than assumed to cancel. $\mathrm{BF}>1$ favours HSA steady. "
         r"The main cell is in bold and is the only one run at three seeds; its "
         r"Monte Carlo standard error is in the text.}"),
        r"\label{tab:conditional-ml}", r"\scriptsize",
        r"\begin{tabular}{llrrrrrrr}", r"\toprule",
        (r"Price & Activity & $\log m(\pi,N,x)$ & $\log m(N)$ & $\log m(\pi,x)$ "
         r"& $\log m(x)$ & HSA & CES & BF \\"),
        (r" &  & HSA & HSA & CES &  & cond. & cond. &  \\"),
        r"\midrule",
    ]
    for price in PRICES:
        for i, activity in enumerate(ACTIVITIES):
            sub = ok[(ok.price == price) & (ok.activity == activity)]
            if sub.empty:
                continue
            row = sub.mean(numeric_only=True)
            cells = [
                price if i == 0 else "",
                activity,
                f"{row['log_m_joint_HSA']:.1f}",
                f"{row['log_m_N_HSA']:.1f}",
                f"{row['log_m_joint_CES']:.1f}",
                f"{row['log_m_x']:.1f}",
                f"{row['log_m_HSA_cond']:.1f}",
                f"{row['log_m_CES_cond']:.1f}",
                f"{row['BF_HSA_CES']:.1f}",
            ]
            if (price, activity) == MAIN:
                cells = [r"\textbf{" + c + "}" if c else c for c in cells]
            lines.append(" & ".join(cells) + r" \\")
        lines.append(r"\midrule")
    lines[-1] = r"\bottomrule"
    lines += [r"\end{tabular}", r"\end{table}", ""]

    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "conditional_ml.tex").write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {(OUT / 'conditional_ml.tex').relative_to(ROOT)}")

    main_rows = ok[(ok.price == MAIN[0]) & (ok.activity == MAIN[1])]
    delta = main_rows["Delta_log_m"].to_numpy(float)
    macros = [
        "% Generated by scripts/make_conditional_ml_table.py; do not edit by hand.",
        rf"\providecommand{{\CmlMainDelta}}{{{delta.mean():+.2f}}}",
        rf"\providecommand{{\CmlMainBF}}{{{np.exp(delta.mean()):.0f}}}",
        rf"\providecommand{{\CmlMainSeeds}}{{{len(delta)}}}",
        rf"\providecommand{{\CmlCellCount}}{{{len(ok.groupby(['price', 'activity']))}}}",
    ]
    if len(delta) > 1:
        mcse = float(delta.std(ddof=1) / np.sqrt(len(delta)))
        macros += [
            rf"\providecommand{{\CmlMainMcse}}{{{mcse:.2f}}}",
            rf"\providecommand{{\CmlMainBFLow}}{{{np.exp(delta.min()):.0f}}}",
            rf"\providecommand{{\CmlMainBFHigh}}{{{np.exp(delta.max()):.0f}}}",
        ]
    # How much of the Monte Carlo noise is the firm-count block: the reason the
    # uncertainty is what it is, rather than a bare number.
    for column, name in (("log_m_N_HSA", "CmlSdMN"), ("log_m_joint_CES", "CmlSdCes")):
        if len(main_rows) > 1:
            macros.append(
                rf"\providecommand{{\{name}}}{{{main_rows[column].std(ddof=1):.3f}}}"
            )
    not_identified = int(table["error"].notna().sum()) if "error" in table else 0
    macros.append(rf"\providecommand{{\CmlNotIdentified}}{{{not_identified}}}")

    MACROS.parent.mkdir(parents=True, exist_ok=True)
    MACROS.write_text("\n".join(macros) + "\n", encoding="utf-8")
    print(f"wrote {MACROS.relative_to(ROOT)}")
    print(ok[["price", "activity", "seed", "Delta_log_m", "BF_HSA_CES"]].to_string(index=False))


if __name__ == "__main__":
    main()
